version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily" 
    labels:
      - "dependabot: dependencies"
      - "dependabot: gradle"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependabot: dependencies"
      - "dependabot: github-actions"
