name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "**.java"
      - "**gradle**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: "8"
        distribution: "temurin"
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
        
    - name: Gradle build
      run: ./gradlew build
