name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "**.java"
      - "**gradle**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
        cache: gradle
        
    - name: Gradle build
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: build --no-daemon
