name: CI

on:
  push:
    branches:
      - "main"
    paths:
      - "**.java"
      - "**.kts"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "**.java"
      - "**.kts"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: "8"
        distribution: "temurin"
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
        
    - name: Gradle build
      run: ./gradlew build
