name: Release

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Install GPG signing key
        run: echo "${{ secrets.GPG_SIGNING_KEY }}" > private.gpg

      - name: Publish to Reposilite
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish -Psigning.secretKeyRingFile=private.gpg -Psigning.password=${{ secrets.GPG_SIGNING_KEY_PASSWORD }} -Psigning.keyId=${{ secrets.GPG_SIGNING_KEY_ID }}
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
